#!/bin/sh
#
# sshd        Starts sshd.
#


umask 077

start() {
	printf "Starting mount: "
	mkdir /tmp/hulk; mount -t 9p -o trans=virtio,version=9p2000.L hostshare /tmp/hulk; cd /tmp/hulk;
	echo "OK"
}
stop() {
	umount /tmp/hulk
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
